name: Manage Labels

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  manage-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create Labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = [
              { name: 'bug', color: 'd73a4a', description: 'Something isn\'t working' },
              { name: 'enhancement', color: 'a2eeef', description: 'New feature or request' },
              { name: 'documentation', color: '0075ca', description: 'Improvements or additions to documentation' },
              { name: 'good first issue', color: '7057ff', description: 'Good for newcomers' },
              { name: 'help wanted', color: '008672', description: 'Extra attention is needed' },
              { name: 'invalid', color: 'e4e669', description: 'This doesn\'t seem right' },
              { name: 'question', color: 'd876e3', description: 'Further information is requested' },
              { name: 'wontfix', color: 'ffffff', description: 'This will not be worked on' },
              { name: 'dependencies', color: '0366d6', description: 'Pull requests that update a dependency file' },
              { name: 'javascript', color: 'f1e05a', description: 'JavaScript related' },
              { name: 'typescript', color: '3178c6', description: 'TypeScript related' },
              { name: 'nextjs', color: '000000', description: 'Next.js related' },
              { name: 'react', color: '61dafb', description: 'React related' },
              { name: 'tailwindcss', color: '38bdf8', description: 'Tailwind CSS related' },
              { name: 'stale', color: '93c5fd', description: 'Stale issue or PR' }
            ];
            
            for (const label of labels) {
              try {
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  color: label.color,
                  description: label.description
                });
                console.log(`Created label: ${label.name}`);
              } catch (error) {
                if (error.status === 422) {
                  console.log(`Label ${label.name} already exists`);
                } else {
                  console.error(`Error creating label ${label.name}:`, error);
                }
              }
            }
